export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODES = {
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  LOAN_NOT_FOUND: 'LOAN_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;